"""initial schema

Revision ID: 9e10fea3f92c
Revises: 
Create Date: 2026-05-12 20:19:55.994045

"""
from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9e10fea3f92c'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('plans',
    sa.Column('plan_id', sa.String(length=32), nullable=False),
    sa.Column('plan_name', sa.String(length=120), nullable=False),
    sa.Column('covered_benefits', sa.JSON(), nullable=False),
    sa.Column('exclusions', sa.JSON(), nullable=False),
    sa.Column('copay_percent', sa.Float(), nullable=False),
    sa.Column('coverage_tiers', sa.JSON(), nullable=False),
    sa.Column('annual_limit_default', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('plan_id')
    )
    op.create_table('providers',
    sa.Column('provider_id', sa.String(length=32), nullable=False),
    sa.Column('name_en', sa.String(length=160), nullable=False),
    sa.Column('name_ar', sa.String(length=160), nullable=False),
    sa.Column('provider_type', sa.String(length=16), nullable=False),
    sa.Column('network_tier', sa.String(length=24), nullable=False),
    sa.Column('city', sa.String(length=64), nullable=False),
    sa.Column('license_number', sa.String(length=48), nullable=False),
    sa.Column('license_expiry', sa.Date(), nullable=False),
    sa.Column('contracted_rates', sa.JSON(), nullable=False),
    sa.Column('performance_score', sa.Float(), nullable=False),
    sa.Column('fraud_risk_score', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('provider_id')
    )
    op.create_table('members',
    sa.Column('member_id', sa.String(length=32), nullable=False),
    sa.Column('full_name_en', sa.String(length=120), nullable=False),
    sa.Column('full_name_ar', sa.String(length=120), nullable=False),
    sa.Column('national_id', sa.String(length=32), nullable=False),
    sa.Column('dob', sa.Date(), nullable=False),
    sa.Column('gender', sa.String(length=16), nullable=False),
    sa.Column('plan_id', sa.String(length=32), nullable=False),
    sa.Column('policy_start', sa.Date(), nullable=False),
    sa.Column('policy_end', sa.Date(), nullable=False),
    sa.Column('policy_status', sa.String(length=16), nullable=False),
    sa.Column('annual_limit', sa.Float(), nullable=False),
    sa.Column('used_amount', sa.Float(), nullable=False),
    sa.Column('deductible', sa.Float(), nullable=False),
    sa.Column('deductible_met', sa.Float(), nullable=False),
    sa.Column('primary_member_id', sa.String(length=32), nullable=True),
    sa.ForeignKeyConstraint(['plan_id'], ['plans.plan_id'], ),
    sa.ForeignKeyConstraint(['primary_member_id'], ['members.member_id'], ),
    sa.PrimaryKeyConstraint('member_id'),
    sa.UniqueConstraint('national_id')
    )
    op.create_table('claims',
    sa.Column('claim_id', sa.String(length=40), nullable=False),
    sa.Column('claim_type', sa.String(length=16), nullable=False),
    sa.Column('member_id', sa.String(length=32), nullable=False),
    sa.Column('provider_id', sa.String(length=32), nullable=False),
    sa.Column('service_date', sa.Date(), nullable=False),
    sa.Column('submission_date', sa.DateTime(), nullable=False),
    sa.Column('diagnosis_codes', sa.JSON(), nullable=False),
    sa.Column('procedure_codes', sa.JSON(), nullable=False),
    sa.Column('line_items', sa.JSON(), nullable=False),
    sa.Column('clinical_notes', sa.Text(), nullable=True),
    sa.Column('total_billed', sa.Float(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.ForeignKeyConstraint(['member_id'], ['members.member_id'], ),
    sa.ForeignKeyConstraint(['provider_id'], ['providers.provider_id'], ),
    sa.PrimaryKeyConstraint('claim_id')
    )
    op.create_table('audit_logs',
    sa.Column('log_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('claim_id', sa.String(length=40), nullable=False),
    sa.Column('event_type', sa.String(length=40), nullable=False),
    sa.Column('event_data', sa.JSON(), nullable=False),
    sa.Column('actor', sa.String(length=48), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('success', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['claim_id'], ['claims.claim_id'], ),
    sa.PrimaryKeyConstraint('log_id')
    )
    op.create_table('decisions',
    sa.Column('decision_id', sa.String(length=40), nullable=False),
    sa.Column('claim_id', sa.String(length=40), nullable=False),
    sa.Column('decision_type', sa.String(length=32), nullable=False),
    sa.Column('decided_at', sa.DateTime(), nullable=False),
    sa.Column('decided_by', sa.String(length=48), nullable=False),
    sa.Column('amount_approved', sa.Float(), nullable=False),
    sa.Column('amount_denied', sa.Float(), nullable=False),
    sa.Column('member_responsibility', sa.Float(), nullable=False),
    sa.Column('confidence_score', sa.Float(), nullable=False),
    sa.Column('reasoning', sa.Text(), nullable=False),
    sa.Column('policy_citations', sa.JSON(), nullable=False),
    sa.Column('flags', sa.JSON(), nullable=False),
    sa.Column('stage_results', sa.JSON(), nullable=False),
    sa.Column('eob_en', sa.Text(), nullable=True),
    sa.Column('eob_ar', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['claim_id'], ['claims.claim_id'], ),
    sa.PrimaryKeyConstraint('decision_id'),
    sa.UniqueConstraint('claim_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('decisions')
    op.drop_table('audit_logs')
    op.drop_table('claims')
    op.drop_table('members')
    op.drop_table('providers')
    op.drop_table('plans')
    # ### end Alembic commands ###
